channels:
  - reason: "technical issues"
    id: "1432408337055613009"
    icon: "ğŸ› ï¸"
  
  - reason: "game-related questions"
    id: "1432408383524180130"
    icon: "ğŸ®"

  - reason: "donations & payments"
    id: "1432408434741088307"
    icon: "ğŸ’°"

  - reason: "report or complaint"
    id: "1432424870993727488"
    icon: "ğŸš©"
  
messages:
  embeds:
    create_ticket:
      title: "ğŸŸï¸ Need help?"
      description : "Please create a ticket using select menu below: "
      color: red
        
    ticket_created:
      name: "{icon}-{name}-ticket"
      topic: "{reason} | {user} | {date} "
      title: "ğŸŸï¸ Ticket: {reason} "
      description: "\n\n**Detailed description**: \n{desc} "
      color: orange
      mention: "{user} created a ticket: "
      channel_mention: "Ticket created! Your channel - {channel}"

    ticket_moved:
      name: "{new}â†{old}"
      title: "Ticket moved!"
      description: "Created by: `{creator}`\nMoved by: `{moder}`"
      color: yellow

    business_hours:
      title: "**Oops! You've reached us after hours.**"
      description: "### We will respond to your ticket when we're back online: \n{context}"
      image_url: "https://i.ibb.co/TqpbTxZz/closed.png"
      timezone: "Europe/Kyiv"
      weekdays: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
      closed: "Closed"
      hours:
        0: {"from":"08:00", "to":"22:00"} #Mon
        1: {"from":"08:00", "to":"22:00"} #Tue
        2: {"from":"08:00", "to":"22:00"} #Wed
        3: {"from":"08:00", "to":"22:00"} #Thu
        4: {"from":"08:00", "to":"22:00"} #Fri
        5: {"from":"10:00", "to":"18:00"} #Sat
        6: null #Sun closed

  modals:
    create_ticket:
      title: "New ticket"
      label_reason: "Ticket reason"
      placeholder_reason: "Please choose a ticket reason..."
      description_reason: "Create a ticket with reason: {reason}"
      label_desc: "Detailed description"
      placeholder_desc: "Please explain in detail what happened/is not working or what request you would like to make..."
      desc_min_length: 4
      desc_max_length: 1600

    move_ticket:
      title: "Move Ticket"
      label_reason: "New ticket reason"
      placeholder_reason: "Please choose new ticket reason"
      description_reason: "Set new ticket reason: {reason}"

  buttons:
    create_ticket: "Create Ticket"
    close_ticket: "Close ticket"
    close_confirm: "Confirm"
    close_ticket_no_permission: "You don't have permission to close tickets"
    move_ticket: "Move ticket"
    move_ticket_no_permission: "You don't have permission to move tickets"
