channels:
  - reason: "–¢–µ—Ö–Ω—ñ—á–Ω—ñ –ø–∏—Ç–∞–Ω–Ω—è"
    id: "1445751592786591804"
    icon: "üõ†Ô∏è"
  
  - reason: "–Ü–≥—Ä–æ–≤—ñ –º–æ–º–µ–Ω—Ç–∏"
    id: "1445751644296843385"
    icon: "üéÆ"

  - reason: "–î–æ–Ω–∞—Ç–∏ —Ç–∞ –ø–ª–∞—Ç–µ–∂—ñ"
    id: "1445751683723301035"
    icon: "üí∞"

  - reason: "–°–∫–∞—Ä–≥–∞ –Ω–∞ –≥—Ä–∞–≤—Ü—è/–ø–µ—Ä—Å–æ–Ω–∞–ª"
    id: "1445751730376675349"
    icon: "üö©"
  
messages:
  embeds:
    ticket_reason_select:
      title: "üéüÔ∏è Need help?"
      description : "Please create a ticket using select menu below: "
      option: "Create a ticket with reason: {reason}"
      placeholder: "üéüÔ∏è Choose your ticket reason..."
      color: red
        
    ticket_created:
      name: "{icon}-{name}-ticket"
      topic: "{reason} | {user} | {date} "
      title: "üéüÔ∏è Ticket: {reason} "
      description: "**Nickname:** {name} \n**Time of event/incident:** {time} \n\n **Detailed description**: \n{desc} "
      color: orange
      mention: "{user} created a ticket: "
      channel_mention: "Ticket created! Your channel - {channel}"

    ticket_moved:
      name: "{new}‚Üê{old}"

    business_hours:
      title: "**Oops! You've reached us after hours.**"
      description: "### We will respond to your ticket when we're back online: \n{context}"
      image_url: "https://i.ibb.co/TqpbTxZz/closed.png"
      timezone: "Europe/Kyiv"
      weekdays: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
      closed: "Closed"
      hours:
        0: {"from":"08:00", "to":"22:00"} #Mon
        1: {"from":"08:00", "to":"22:00"} #Tue
        2: {"from":"08:00", "to":"22:00"} #Wed
        3: {"from":"08:00", "to":"22:00"} #Thu
        4: {"from":"08:00", "to":"22:00"} #Fri
        5: {"from":"10:00", "to":"18:00"} #Sat
        6: null #Sun closed

  modals:
    create_ticket:
      title: "New ticket"
      label_reason: "Ticket reason"
      placeholder_reason: "Please choose a ticket reason..."
      label_name: "Your in-game Name"
      label_data: "Time of event/incident"
      label_desc: "Detailed description"
      placeholder_desc: "Please explain in detail what happened/is not working or what request you would like to make..."
      desc_min_length: 4
      desc_max_length: 1600

    move_ticket:
      title:

  buttons:
    close_ticket: "–ó–∞–∫—Ä–∏—Ç–∏ —Ç–∏–∫–µ—Ç"
    close_ticket_no_permission: "–£ –≤–∞—Å –Ω–µ–º–∞—î –¥–æ–∑–≤–æ–ª—É –Ω–∞ –∑–∞–∫—Ä–∏—Ç—Ç—è —Ç–∏–∫–µ—Ç—ñ–≤"
    move_ticket: "–ü–µ—Ä–µ–º—ñ—Å—Ç–∏—Ç–∏ —Ç–∏–∫–µ—Ç"
    move_ticket_no_permission: "–£ –≤–∞—Å –Ω–µ–º–∞—î –¥–æ–∑–≤–æ–ª—É –Ω–∞ –ø–µ—Ä–µ–º—ñ—â–µ–Ω–Ω—è —Ç–∏–∫–µ—Ç—ñ–≤"
